name: 🚀 Pull-request
description: Pull-request template
title: "<title>"
body:
  - type: textarea
    attribute:
      label: Pull request purpose
      description: What the purpose of this pull requeste?
    validation:
      required: false
  - type: textarea
    attribute:
      label: What has been modified
      description: describe which file you modified and what you modified
    validation:
      required: false